language: node_js
cache: yarn

node_js: "10"

after_success:
  - npm install --no-save coveralls
  - npx nyc report --reporter=text-lcov | npx coveralls

deploy:
  provider: npm
  email: nieltansah+npmjs@gmail.com
  api_key: $NPM_API_KEY

  skip_cleanup: true
  on:
    tags: true
